spring:
  config:
    import:
      - 'classpath:/yml/application-oauth.yml'
      - 'classpath:/yml/application-logging.yml'
  application:
    name: chat
  thymeleaf:    # 타임리프 설정
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource: # DB 설정
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/chat
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8087
  error:
    path: /error
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false

file:
  upload:
    path: ./uploads